language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"

install:
  # Install node modules
  - npm install

  # Install gem and sass
  - ruby --version
  - wget http://production.cf.rubygems.org/rubygems/rubygems-2.1.7.tgz
  - tar xvf rubygems-2.1.7.tgz
  - cd rubygems-2.1.7
  - sudo ruby setup.rb
  - cd ..
  - gem --version
  - gem install sass
  - sass --version

  # Install libsass/sassc
  - git clone https://github.com/hcatlin/libsass.git libsass
  - export SASS_LIBSASS_PATH=$PWD/libsass
  - git clone https://github.com/hcatlin/sassc.git sassc
  - cd sassc
  - make
  - sudo ln -s $PWD/bin/sassc /usr/local/bin/sassc
  - cd ..
  - sassc -h

notifications:
  email: false
